--  Generated by gperfhash
package Sqlite3_H.Perfect_Hash is

   pragma Preelaborate;

   function Hash (S : String) return Natural;

   --  Returns true if the string <b>S</b> is a keyword.
   function Is_Keyword (S : in String) return Boolean;

   type Name_Access is access constant String;
   type Keyword_Array is array (Natural range <>) of Name_Access;
   Keywords : constant Keyword_Array;
private

   K_0             : aliased constant String := "ABORT";
   K_1             : aliased constant String := "ACTION";
   K_2             : aliased constant String := "ADD";
   K_3             : aliased constant String := "AFTER";
   K_4             : aliased constant String := "ALL";
   K_5             : aliased constant String := "ALTER";
   K_6             : aliased constant String := "ANALYZE";
   K_7             : aliased constant String := "AND";
   K_8             : aliased constant String := "AS";
   K_9             : aliased constant String := "ASC";
   K_10            : aliased constant String := "ATTACH";
   K_11            : aliased constant String := "AUTOINCREMENT";
   K_12            : aliased constant String := "BEFORE";
   K_13            : aliased constant String := "BEGIN";
   K_14            : aliased constant String := "BETWEEN";
   K_15            : aliased constant String := "BY";
   K_16            : aliased constant String := "CASCADE";
   K_17            : aliased constant String := "CASE";
   K_18            : aliased constant String := "CAST";
   K_19            : aliased constant String := "CHECK";
   K_20            : aliased constant String := "COLLATE";
   K_21            : aliased constant String := "COLUMN";
   K_22            : aliased constant String := "COMMIT";
   K_23            : aliased constant String := "CONFLICT";
   K_24            : aliased constant String := "CONSTRAINT";
   K_25            : aliased constant String := "CREATE";
   K_26            : aliased constant String := "CROSS";
   K_27            : aliased constant String := "CURRENT_DATE";
   K_28            : aliased constant String := "CURRENT_TIME";
   K_29            : aliased constant String := "CURRENT_TIMESTAMP";
   K_30            : aliased constant String := "DATABASE";
   K_31            : aliased constant String := "DEFAULT";
   K_32            : aliased constant String := "DEFERRABLE";
   K_33            : aliased constant String := "DEFERRED";
   K_34            : aliased constant String := "DELETE";
   K_35            : aliased constant String := "DESC";
   K_36            : aliased constant String := "DETACH";
   K_37            : aliased constant String := "DISTINCT";
   K_38            : aliased constant String := "DROP";
   K_39            : aliased constant String := "EACH";
   K_40            : aliased constant String := "ELSE";
   K_41            : aliased constant String := "END";
   K_42            : aliased constant String := "ESCAPE";
   K_43            : aliased constant String := "EXCEPT";
   K_44            : aliased constant String := "EXCLUSIVE";
   K_45            : aliased constant String := "EXISTS";
   K_46            : aliased constant String := "EXPLAIN";
   K_47            : aliased constant String := "FAIL";
   K_48            : aliased constant String := "FOR";
   K_49            : aliased constant String := "FOREIGN";
   K_50            : aliased constant String := "FROM";
   K_51            : aliased constant String := "FULL";
   K_52            : aliased constant String := "GLOB";
   K_53            : aliased constant String := "GROUP";
   K_54            : aliased constant String := "HAVING";
   K_55            : aliased constant String := "IF";
   K_56            : aliased constant String := "IGNORE";
   K_57            : aliased constant String := "IMMEDIATE";
   K_58            : aliased constant String := "IN";
   K_59            : aliased constant String := "INDEX";
   K_60            : aliased constant String := "INDEXED";
   K_61            : aliased constant String := "INITIALLY";
   K_62            : aliased constant String := "INNER";
   K_63            : aliased constant String := "INSERT";
   K_64            : aliased constant String := "INSTEAD";
   K_65            : aliased constant String := "INTERSECT";
   K_66            : aliased constant String := "INTO";
   K_67            : aliased constant String := "IS";
   K_68            : aliased constant String := "ISNULL";
   K_69            : aliased constant String := "JOIN";
   K_70            : aliased constant String := "KEY";
   K_71            : aliased constant String := "LEFT";
   K_72            : aliased constant String := "LIKE";
   K_73            : aliased constant String := "LIMIT";
   K_74            : aliased constant String := "MATCH";
   K_75            : aliased constant String := "NATURAL";
   K_76            : aliased constant String := "NO";
   K_77            : aliased constant String := "NOT";
   K_78            : aliased constant String := "NOTNULL";
   K_79            : aliased constant String := "NULL";
   K_80            : aliased constant String := "OF";
   K_81            : aliased constant String := "OFFSET";
   K_82            : aliased constant String := "ON";
   K_83            : aliased constant String := "OR";
   K_84            : aliased constant String := "ORDER";
   K_85            : aliased constant String := "OUTER";
   K_86            : aliased constant String := "PLAN";
   K_87            : aliased constant String := "PRAGMA";
   K_88            : aliased constant String := "PRIMARY";
   K_89            : aliased constant String := "QUERY";
   K_90            : aliased constant String := "RAISE";
   K_91            : aliased constant String := "REFERENCES";
   K_92            : aliased constant String := "REGEXP";
   K_93            : aliased constant String := "REINDEX";
   K_94            : aliased constant String := "RELEASE";
   K_95            : aliased constant String := "RENAME";
   K_96            : aliased constant String := "REPLACE";
   K_97            : aliased constant String := "RESTRICT";
   K_98            : aliased constant String := "RIGHT";
   K_99            : aliased constant String := "ROLLBACK";
   K_100           : aliased constant String := "ROW";
   K_101           : aliased constant String := "SAVEPOINT";
   K_102           : aliased constant String := "SELECT";
   K_103           : aliased constant String := "SET";
   K_104           : aliased constant String := "TABLE";
   K_105           : aliased constant String := "TEMP";
   K_106           : aliased constant String := "TEMPORARY";
   K_107           : aliased constant String := "THEN";
   K_108           : aliased constant String := "TO";
   K_109           : aliased constant String := "TRANSACTION";
   K_110           : aliased constant String := "TRIGGER";
   K_111           : aliased constant String := "UNION";
   K_112           : aliased constant String := "UNIQUE";
   K_113           : aliased constant String := "UPDATE";
   K_114           : aliased constant String := "USING";
   K_115           : aliased constant String := "VACUUM";
   K_116           : aliased constant String := "VALUES";
   K_117           : aliased constant String := "VIEW";
   K_118           : aliased constant String := "VIRTUAL";
   K_119           : aliased constant String := "WHEN";
   K_120           : aliased constant String := "WHERE";

   Keywords : constant Keyword_Array := (
      K_0'Access, K_1'Access, K_2'Access, K_3'Access,
      K_4'Access, K_5'Access, K_6'Access, K_7'Access,
      K_8'Access, K_9'Access, K_10'Access, K_11'Access,
      K_12'Access, K_13'Access, K_14'Access, K_15'Access,
      K_16'Access, K_17'Access, K_18'Access, K_19'Access,
      K_20'Access, K_21'Access, K_22'Access, K_23'Access,
      K_24'Access, K_25'Access, K_26'Access, K_27'Access,
      K_28'Access, K_29'Access, K_30'Access, K_31'Access,
      K_32'Access, K_33'Access, K_34'Access, K_35'Access,
      K_36'Access, K_37'Access, K_38'Access, K_39'Access,
      K_40'Access, K_41'Access, K_42'Access, K_43'Access,
      K_44'Access, K_45'Access, K_46'Access, K_47'Access,
      K_48'Access, K_49'Access, K_50'Access, K_51'Access,
      K_52'Access, K_53'Access, K_54'Access, K_55'Access,
      K_56'Access, K_57'Access, K_58'Access, K_59'Access,
      K_60'Access, K_61'Access, K_62'Access, K_63'Access,
      K_64'Access, K_65'Access, K_66'Access, K_67'Access,
      K_68'Access, K_69'Access, K_70'Access, K_71'Access,
      K_72'Access, K_73'Access, K_74'Access, K_75'Access,
      K_76'Access, K_77'Access, K_78'Access, K_79'Access,
      K_80'Access, K_81'Access, K_82'Access, K_83'Access,
      K_84'Access, K_85'Access, K_86'Access, K_87'Access,
      K_88'Access, K_89'Access, K_90'Access, K_91'Access,
      K_92'Access, K_93'Access, K_94'Access, K_95'Access,
      K_96'Access, K_97'Access, K_98'Access, K_99'Access,
      K_100'Access, K_101'Access, K_102'Access, K_103'Access,
      K_104'Access, K_105'Access, K_106'Access, K_107'Access,
      K_108'Access, K_109'Access, K_110'Access, K_111'Access,
      K_112'Access, K_113'Access, K_114'Access, K_115'Access,
      K_116'Access, K_117'Access, K_118'Access, K_119'Access,
      K_120'Access);
end Sqlite3_H.Perfect_Hash;
