description = "Ada Database Objects (SQLite)"
tags = ["database", "uml", "sql", "sqlite"]
name = "ado_sqlite"
version = "2.5.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["ado_sqlite.gpr"]
website = "https://gitlab.com/stcarrez/ada-ado"
long-description = """

[![Build Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-ado/badges/build.json)](https://porion.vacs.fr/porion/projects/view/ada-ado/summary)
[![Test Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-ado/badges/tests.json)](https://porion.vacs.fr/porion/projects/view/ada-ado/xunits)
[![Coverage](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-ado/badges/coverage.json)](https://porion.vacs.fr/porion/projects/view/ada-ado/summary)
[![Documentation Status](https://readthedocs.org/projects/ada-ado/badge/?version=latest)](https://ada-ado.readthedocs.io/en/latest/?badge=latest)

This is the SQLite or SQLCipher driver for the Ada Database Objects library.

The choice between SQLite and SQLCipher is controlled by the `ADO_USE_SQLCIPHER` gpr external variable.
Use `-XADO_USE_SQLCIPHER=yes` if you want to use the SQLCipher support.  The database encryption key
is configured by using a `pragma key`.

"""

[[depends-on]]
ado = "^2.5.0"
libsqlite3 = "any"

[gpr-externals]
ADO_USE_SQLCIPHER = ["yes", "no"]

[configuration]
disabled = true

[[pins]]
ado = { path='..' }
